
name: Build VaultGuard

on:

  push:

    branches: [ main ]

  workflow_dispatch:

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.12"

      - run: sudo apt-get install -y python3-tk xclip

      - run: pip install -r requirements.txt pyinstaller

      - run: pyinstaller --onefile --windowed --name VaultGuard vaultguard.py

      - uses: actions/upload-artifact@v4

        with:

          name: VaultGuard-Linux

          path: dist/VaultGuard

  build-windows:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.12"

      - run: pip install -r requirements.txt pyinstaller

      - run: pyinstaller --onefile --windowed --name VaultGuard vaultguard.py

      - uses: actions/upload-artifact@v4

        with:

          name: VaultGuard-Windows

          path: dist/VaultGuard.exe

  build-mac:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:

          python-version: "3.12"

      - run: pip install -r requirements.txt pyinstaller

      - run: pyinstaller --onefile --windowed --name VaultGuard vaultguard.py

      - uses: actions/upload-artifact@v4

        with:

          name: VaultGuard-Mac

          path: dist/VaultGuard

